[alias]
br = "build -p gmf-remote --release --target x86_64-unknown-linux-musl"
b = "build -p gmf --release --target x86_64-unknown-linux-musl"
b-win = "build -p gmf --release --target x86_64-pc-windows-gnu"

[build]
target = "x86_64-unknown-linux-musl"